# [OPTIONAL] AWS Environment
env:
  account: "xxxxxxxxxxxx"
  region: ap-northeast-1

# Stack name
stackName: NotifyBilling

# Slack Webhook URL
slackWebhookUrl: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# Group By ("SERVICE" / "LINKED_ACCOUNT")
groupBy: SERVICE
